param(
  # nomi degli stack CDK
  [string] $ImgStack = "ImgPipeline",
  [string] $PacsStack = "PacsApi"
)

Write-Host "🔄 Recupero Outputs dallo stack $ImgStack..."
$imgOutputs = (aws cloudformation describe-stacks --stack-name $ImgStack | ConvertFrom-Json).Stacks[0].Outputs

Write-Host "🔄 Recupero Outputs dallo stack $PacsStack..."
$pacsOutputs = (aws cloudformation describe-stacks --stack-name $PacsStack | ConvertFrom-Json).Stacks[0].Outputs

function Get-OutputValue {
  param($Outputs, $Key)
  $match = $Outputs | Where-Object { $_.OutputKey -eq $Key }
  if ($match) { return $match[0].OutputValue }
  else { return "" }
}



# API Gateway base URL
$apiBase = Get-OutputValue $imgOutputs "ProcessingApiEndpoint"

# Load Balancer DNS del PACS API
$pacsDns = Get-OutputValue $pacsOutputs "PacsApiLB"

# ARN del topic SNS
$resultsTopicArn = Get-OutputValue $imgOutputs "ImageResultsTopicArn"

# Code SQS
$req1 = Get-OutputValue $imgOutputs "ImageRequestsQueueUrlprocessing1"
$res1 = Get-OutputValue $imgOutputs "ImageResultsQueueUrlprocessing1"
$req6 = Get-OutputValue $imgOutputs "ImageRequestsQueueUrlprocessing6"
$res6 = Get-OutputValue $imgOutputs "ImageResultsQueueUrlprocessing6"

# Scrivo env.ps1
$envFile = Join-Path -Path (Get-Location) -ChildPath "gen_env/env.ps1"
@"
# Autogenerated (dot-source me to import)
`$Env:API_BASE         = '$apiBase'
`$Env:PACS_API_BASE    = 'http://$pacsDns'
`$Env:RESULTS_TOPIC_ARN = '$resultsTopicArn'

`$Env:REQ1_QUEUE       = '$req1'
`$Env:RES1_QUEUE       = '$res1'
`$Env:REQ6_QUEUE       = '$req6'
`$Env:RES6_QUEUE       = '$res6'
"@ | Out-File -FilePath $envFile -Encoding UTF8 -Force

Write-Host "✅ Ho generato env.ps1 in $envFile"
Write-Host "Per importare le variabili, esegui in PowerShell:"
Write-Host " . .\gen_env\env.ps1"
