version: "3.9"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    privileged: true
    environment:
      SHARED_DIRECTORY: /data
    volumes:
      - ./data:/data          # persistenza host↔container
    ports:
      - "111:111/udp"
      - "111:111/tcp"
      - "2049:2049"           # NFS v4

